### ISSUE TITLE
tech/html/select nvda/firefox

### ISSUE THREAD

**Issue by smhigley** [accessibilitysupported/a11ysupport.io#105]
This Support Point submission is for the test [HTML select element test](/tests/tech__html__select)

It looks like I marked the focus differently than you did, though I didn't notice until opening the issue. I chose "within target" since the keyboard focus remains on the select element, but I wasn't intending to actually propose that be changed, so please ignore that unless you want to change it for all tests 😝.

The actual changes were that NVDA + FF has full support for optgroups. The last test change is just a subjective suggestion to mark the posinset test a pass, since announcing position & size of set when expanded but not collapsed seems like the most accurate UX choice if trying to match visual experience.

meta info

| property | value |
| --- | --- |
| title | tech/html/select |
| at | nvda |
| at_version | 2019.2.1 |
| browser | firefox |
| browser_version | 73 |
| os_version | 1909 |

optgroup element: convey an appropriate name

| property | new value | old value |
| --- | --- | --- |
| feature_id | html/optgroup_element | - |
| feature_assertion_id | convey_name | - |
| output_1_before_focus | within target | before target |
| output_1_output | "Meats grouping. Chicken 1 of 2 level 2." | not conveyed |
| output_1_result | pass | fail |

optgroup element: convey an appropriate role

| property | new value | old value |
| --- | --- | --- |
| feature_id | html/optgroup_element | - |
| feature_assertion_id | convey_role | - |
| output_1_before_focus | within target | before target |
| output_1_output | "Meats grouping" | not conveyed |
| output_1_result | pass | fail |

optgroup element: convey the boundaries of the element

| property | new value | old value |
| --- | --- | --- |
| feature_id | html/optgroup_element | - |
| feature_assertion_id | convey_boundaries | - |
| output_1_output | optgroup announced when entering, and position of options within optgroup convey boundaries. | optgroup boundaries were not conveyed |
| output_1_result | pass | fail |

option element: convey information about the position the option in the list

| property | new value | old value |
| --- | --- | --- |
| feature_id | html/option_element | - |
| feature_assertion_id | convey_posinset | - |
| output_1_result | pass | partial |

== begin notes ==
only conveyed when expanded (this matches visual experience)
== end notes ==

**Comment by mfairchild365** [comment]
Thank you so much for this @smhigley! Can you confirm your version numbers? It looks like the numbers that I have committed to the project a just a tad out of date.

**Comment by mfairchild365** [comment]
I quickly verified with the latest versions and got the same results, so I went with those. :) Thank you again!

**Comment by smhigley** [comment]
Thanks! Sorry, yeah, I should update NVDA and JAWS on my machine :D
