### ISSUE TITLE
iOS Voiceover GridCell not supported

### ISSUE THREAD

**Issue by gurmukhp** [accessibilitysupported/a11ysupport.io#113]
With iOS 13 on an iPhone 7+ in Safari, when I load the following test URL:
https://a11ysupport.io/tests/aria_gridcell#assertion-aria-gridcell_role-convey_name-vo_ios-ios_saf

No announcement is made about the grid. It looks like VoiceOver on iOS doesn't support it?

**Comment by mfairchild365** [comment]
Good catch, thank you for reporting. This appears to be a regression in VO for iOS + Safari. I'll update the results soon.

**Comment by gurmukhp** [comment]
Great thank you, I've raised this directly with Apple via their Feedback Assistant. I wasn't aware it was a regression, I hope it's an easy fix :)

**Comment by mfairchild365** [comment]
tests have been updated: https://a11ysupport.io/tests/tech__aria__grid
