### ISSUE TITLE
tech/aria/aria-atomic jaws/firefox

### ISSUE THREAD

**Issue by stevefaulkner** [accessibilitysupported/a11ysupport.io#118]
This Support Point submission is for the test [aria-atomic test](/tests/tech__aria__aria-atomic)

meta info

| property | value |
| --- | --- |
| title | tech/aria/aria-atomic |
| at | jaws |
| at_version | 2020.2006.12 |
| browser | firefox |
| browser_version | 79.0b3 (64-bit) |
| os_version | Windows 10 version 1903 |

aria-atomic attribute: convey the false value by only announcing content that has changed

| property | new value | old value |
| --- | --- | --- |
| feature_id | aria/aria-atomic_attribute | - |
| feature_assertion_id | convey_value_false | - |
| output_1_output | has changed | (nothing was conveyed) |
| output_1_result | pass | fail |
| output_1_notes | appears as if JAWS announces "t has changed" but unsure |  |

aria-atomic attribute: convey the true value by announcing all content

| property | new value | old value |
| --- | --- | --- |
| feature_id | aria/aria-atomic_attribute | - |
| feature_assertion_id | convey_value_true | - |
| output_1_output |  Announce only what has changed | (nothing was conveyed) |
| output_1_result | pass | fail |

**Comment by mfairchild365** [comment]
Thank you for reporting this @stevefaulkner - I confirmed your results and updated the data. Thanks again!

(also, I need to spend some time on that form to make it easier to use; but I'm glad you could figure it out)

**Comment by stevefaulkner** [comment]
@mfairchild365 no worries. yeah the form was a little tricky
