### ISSUE TITLE
test aria-busy

### ISSUE THREAD

**Issue by mfairchild365** [accessibilitysupported/a11ysupport.io#122]

**Comment by sandrina-p** [comment]
Hi @mfairchild365 , do you have any plans when testing this attribute? :) 

I was looking for support tests and the only article I found was from 2018 [Short note on aria-busy](https://developer.paciellogroup.com/blog/2018/05/short-note-on-being-busy/).

**Comment by mfairchild365** [comment]
@sandrina-p thanks for the note. I hope to tackle this very soon.

**Comment by mfairchild365** [comment]
@sandrina-p I finished the test. https://a11ysupport.io/tech/aria/aria-busy_attribute

This attribute could in theory have many facets of support, especially around how it is supposed to work with `aria-live`. I didn't get into those details with this test, and instead did a simple test with `aria-busy` on a div, similar to the short note on aria-busy that you referenced. When support improves, it might be worth while to set up more test cases and expectations.

**Comment by sandrina-p** [comment]
Thank you @mfairchild365 !
