### ISSUE TITLE
Re-test aria-modal

### ISSUE THREAD

**Issue by mfairchild365** [accessibilitysupported/a11ysupport.io#125]

**Comment by mfairchild365** [comment]
Tests have been re-run, except for JAWS+FF, which was causing crashes unrelated to aria-modal. Will retest this after FF 79 is released.

**Comment by maddieblack** [comment]
@mfairchild365 Were there any changes when you re-ran the tests?

**Comment by mfairchild365** [comment]
@maddieblack I never got around to re-testing it. I will soon! Thank you for the prompt.

**Comment by mfairchild365** [comment]
@maddieblack I just updated the results in https://github.com/accessibilitysupported/a11ysupport.io/commit/54af89d8a0cd83983e2eb625f07c49cc97a6cae4 

There were no significant changes in support.
