### ISSUE TITLE
html_button(type-button--aria-disabled-true) vo_macos/safari

### ISSUE THREAD

**Issue by RSuraj** [accessibilitysupported/a11ysupport.io#132]
This Support Point submission is for the test [HTML button[type="button" aria-disabled="true"]](/tests/html_button(type-button--aria-disabled-true))

meta info

| property | value |
| --- | --- |
| title | html_button(type-button--aria-disabled-true) |
| at | vo_macos |
| at_version | 10.15.6 |
| browser | safari |
| browser_version | 13.1.2 |
| os_version | 10.15.6 |

no changes (same results were confirmed)

**Comment by mfairchild365** [comment]
Thanks @RSuraj
