### ISSUE TITLE
Update datalist expectation for suggestion changes from MUST to SHOULD/MAY

### ISSUE THREAD

**Issue by WestonThayer** [accessibilitysupported/a11ysupport.io#137]
https://a11ysupport.io/tech/html/datalist_element#support-table-2

I agree that some sort of alert that suggestions have changed seems like a useful UX (especially given that sighted users can see the suggestions changing), I'm not sure that it's a hard requirement after testing various comboboxes and searchboxes (that also offer suggestions) and not hearing any announcement:

- When using NVDA 2020.2 with a native Windows searchbox (like the one in the Windows Settings app), NVDA makes no announcements after typing and the suggestions list updating
- NVDA 2020.2 with Firefox 80.0 announces Firefox's address bar as "combo box, collapsed, Search with Google or enter address, edit, collapsed, has auto complete, blank". After typing the first character, "expanded" is announced, but nothing after that
- JAWS 2020 with Chrome 85 makes no announcements either in Chrome's address bar
- JAWS 2020 with Chrome 85 makes no announcements when typing in google.com's search combobox
- iOS VoiceOver makes no announcements about suggestions when using the search in the Settings app
- MacOS VoiceOver doesn't announce changes to the suggestions in the System Preferences app, unless you have an exact match, in which case it will say "[match] selected"

On the other hand:

- When using Narrator 1809 with a native Windows searchbox (Settings app again), the announcement on focus is "searchbox, find a setting, editing". After typing a key, the announcement is "suggestions available, [number] suggestions"
- When using JAWS 2020 in the same scenario, after typing a key the announcement is "[number] results"
- Narrator also announces "suggestions available", without a number in Edge 85's address bar

At the least, I'd say screen reader users are accustomed to not hearing announcements when suggestions are available. I wonder if suggestions are implied by the combobox or searchbox role.

Some discussion from screen reader vendors and users seems useful in determining what to do here.

**Comment by mfairchild365** [comment]
Thank you for sharing the research here. I’m leaning on making this a SHOULD. Do you think that’s a good strength?

**Comment by WestonThayer** [comment]
I don't feel like I have enough context, would really like to hear from some screen reader users. I don't have the Twitter audience @aardrian does to run a poll (yes, @aardrian this is a shameless attempt to get your feedback on this issue), but could post in web-a11y Slack.

**Comment by aardrian** [comment]
Man, I'm just trying to eat dinner and catch up on _Orphan Black_.

My gut says yeah, shifting to a SHOULD is better.

However, I agree that asking people (ideally SR users) is helpful. The data from a Twitter poll is meh, but the responses a poll garners usually have more insights than the numbers anyway.

If you craft a <240 character tweet with up to 4 choices of <25 words each, I will be happy to tweet it tomorrow at the start of my day.

**Comment by WestonThayer** [comment]
Thanks @aardrian! I'm far too slow on the draw, but would still be very interested if you're still up for a Tweet (no rush though):

> When typing within a combobox or searchbox that has autocompletion suggestions, what do you expect your screen reader to announce?
> 
> - Nothing / echo your input
> - Number of suggestions
> - The top suggestion
> - Other (add comment)

**Comment by aardrian** [comment]
@WestonThayer https://twitter.com/aardrian/status/1306306437191262209
