### ISSUE TITLE
FAQ mentions both WCAG 2.0 and 2.1

### ISSUE THREAD

**Issue by Malvoz** [accessibilitysupported/a11ysupport.io#145]
> This is a community-driven website that aims to help inform developers about what is [accessibility supported](https://www.w3.org/TR/WCAG21/#cc4). In order to conform to WCAG 2.0, you must write code in ways that are supported by assistive technologies (such as screen readers).

The link in this paragraph points to WCAG 2.1, but talks about WCAG 2.0. Is that intentional?

Would it be reasonable to simply say "WCAG" and link to the latest published recommendation (https://www.w3.org/TR/WCAG/) instead perhaps? It's worth mentioning that [WCAG 2.2 is scheduled for realease next year](https://www.w3.org/WAI/standards-guidelines/wcag/#versions).

**Comment by mfairchild365** [comment]
Thank you for this @Malvoz! Changing to “WCAG” seems like a fine solution. Can you put in a PR for that?

**Comment by Malvoz** [comment]
I have a follow-up question first:

> Be sure you conform to [WCAG 2.1 level AA](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.1) and strive to meet the Inclusive Design Principles

There's no "quickref" link to latest version of WCAG, should this instead link to e.g. https://www.w3.org/TR/WCAG/#cc1?

**Comment by mfairchild365** [comment]
Good point. I like the quick ref, but it would also be ideal to future proof this text as much as possible. I’m okay with using the link you provided if you put in a PR.

**Comment by mfairchild365** [comment]
Fixed in https://github.com/accessibilitysupported/a11ysupport.io/pull/155
