### ISSUE TITLE
What license is this module?

### ISSUE THREAD

**Issue by YusukeHirao** [accessibilitysupported/a11ysupport.io#160]
Thanks for publishing to NPM.
But this module doesn't have a license.
So I hesitate to use this.

Please decide the license of this module.

**Comment by mfairchild365** [comment]
License is located at https://github.com/accessibilitysupported/a11ysupport.io/blob/master/LICENSE

it’s included in the module, but there is probably a way to make it more clear in the npm package. I’ll look into that.

**Comment by YusukeHirao** [comment]
@mfairchild365 
Thanks for telling me the location of the license.
The license should be set to package.json for NPM.

Should I do PR?

**Comment by mfairchild365** [comment]
Sure, a PR would be great!
