### ISSUE TITLE
html_svg_inline_with_title nvda/chrome

### ISSUE THREAD

**Issue by kimskovhusandersen** [accessibilitysupported/a11ysupport.io#168]
This Support Point submission is for the test [HTML SVG element with SVG title element](/tests/html_svg_inline_with_title)

meta info

| property | value |
| --- | --- |
| title | html_svg_inline_with_title |
| at | nvda |
| at_version | 2020.4 |
| browser | chrome |
| browser_version | 89 |
| os_version | 20H2 |

no changes (same results were confirmed)

**Comment by mfairchild365** [comment]
@kimskovhusandersen thank you for this. I'll update this soon!
