### ISSUE TITLE
tech/css/css_generated_content_alt: Test does pass in Narrator + Edge

### ISSUE THREAD

**Issue by iansjk** [accessibilitysupported/a11ysupport.io#172]
Hi,

I recently used this feature to fix an edge case in Narrator + Edge (no pun intended...) and the syntax
```css
.some-element::before {
  content: "*" / "alt text"
}
```
Does appear to be supported now in Narrator + Edge.

Narrator version: Unsure how to check; happy to fill in this info with some guidance
Browser version: Edge 90.0.818.56
The OS version: Windows 10, 20H2, OS Build 19042.928 *running within Parallels on OSX Big Sur*
The specific command(s) used to access the target element with the AT (keys used, touch gestures, or voice command): Both scanning through the buttons with Tab/Shift+Tab and using B/Shift+B in scan mode correctly read "Play" for the middle button.
Whether or not you think the test passes or fails and why: Test appears to pass based on reading "Play" rather than a right arrow character.

**Comment by mfairchild365** [comment]
Hi @iansjk, thank you for this report. I'll re-test and update this soon.

**Comment by iansjk** [comment]
Thanks for your hard work! 🙏🏼
