### ISSUE TITLE
(Feature) Making it pretty 😉 

### ISSUE THREAD

**Issue by lemnis** [accessibilitysupported/a11ysupport.io#177]
I love this project but I can see it the data is hard to consume for a newcomer. As such I thought I would spent a evening that create a little hack project, combining 2 projects I love. Caniuse / caniemail & a11ysupport.io, resulting in this frankenstein -> https://lemnis.github.io/caniemail/ 

Only spend a couple of hours on it, so a lot will be broken. Code can be found here: https://github.com/lemnis/caniemail. It lists all the current features of a11ysupport.io.

Not sure yet how much more time I can and want to spend on it, but if there is a lot of interest... 😉

**Comment by mfairchild365** [comment]
This is awesome. Thank you for doing this, @lemnis! I'll keep this in mind for when I inevitably update the design, but I'm not sure when that will be.
