### ISSUE TITLE
tech/aria/aria-invalid talkback/and_chr

### ISSUE THREAD

**Issue by polarathene** [accessibilitysupported/a11ysupport.io#178]
This Support Point submission is for the test [aria-invalid test suite](/tests/tech__aria__aria-invalid)

meta info

| property | value |
| --- | --- |
| title | tech/aria/aria-invalid |
| at | talkback |
| at_version | 9.1 |
| browser | and_chr |
| browser_version | 92 |
| os_version | 10 |

## Test case: Use Swipe right (or alt+right arrow) (Read next item) to navigate forward to `#target2`
Command used: `next_item`

### output
**before:**
```"cats, edit box, error: invalid entry, target 2"```
**after:**
```"cats, edit box, target 2"```

### result for aria-invalid attribute, MUST convey the "true" value, applied to input[type="text"] element

key: aria/aria-invalid_attribute; convey_value_true; applied to: html/input(type-text)_element

### result
**before:**
```pass```
**after:**
```fail```

### note
**before:**
```(empty)```
**after:**
```No difference from "false"```

## Test case: Use Swipe right (or alt+right arrow) (Read next item) to navigate forward to `#target3`
Command used: `next_item`

### output
**before:**
```"cats, edit box, error: invalid grammar, target 3, error: invalid grammar, error: invalid entry, end of field"```
**after:**
```"cats, edit box, target 3"```

## Test case: Use Swipe right (or alt+right arrow) (Read next item) to navigate forward to `#target4`
Command used: `next_item`

### output
**before:**
```"cats, edit box, error: invalid spelling, target 4, error: invalid spelling, error: invalid grammar, end of field"```
**after:**
```"cats, edit box, target 4"```

### result for aria-invalid attribute, MUST NOT convey the "spelling" value, applied to input[type="text"] element

key: aria/aria-invalid_attribute; convey_value_spelling; applied to: html/input(type-text)_element

### result
**before:**
```partial```
**after:**
```pass```

## Test case: Use Swipe right (or alt+right arrow) (Read next item) to navigate forward to `#target5`
Command used: `next_item`

### output
**before:**
```"collapsed, none, popup button, target 5"```
**after:**
```"collapsed, none, menu pop-up button, target 5"```

## Test case: Use Swipe right (or alt+right arrow) (Read next item) to navigate forward to `#target6`
Command used: `next_item`

### output
**before:**
```"collapsed, none, popup button, target 6"```
**after:**
```"collapsed, none, menu pop-up button, target 6"```

**Comment by polarathene** [comment]
Also confirmed on another Android device running Android 9, Chrome 92, Talkback 9.1. Same spoken output.

Firefox is roughly the same with Talkback (no test results for this combination listed on the website), sometimes Talkback support differs vs Chrome, but in this case only the wording and ordering was different. I could submit those again for Firefox if desirable. 

One example I noticed where Talkback differed between browsers was `aria-atomic="true"` working on Firefox as expected but not Chrome. Another was announcing `aria-describedby` on a `li` element in an `aria-live` region (Chrome does this, Firefox ignored it).

Either Talkback has regressed for `aria-invalid` or the two Android devices tested (Huawei with EMUI) behave differently with default Talkback on.

**Comment by mfairchild365** [comment]
Thank you @polarathene, I hope to look at this soon!
