### ISSUE TITLE
tech/aria/aria-current talkback/and_chr

### ISSUE THREAD

**Issue by fchubu** [accessibilitysupported/a11ysupport.io#185]
This Support Point submission is for the test [aria-current attribute](/tests/tech__aria__aria-current)

meta info

| property | value |
| --- | --- |
| title | tech/aria/aria-current |
| at | talkback |
| at_version | 9.1 |
| browser | and_chr |
| browser_version | 92.0 |
| os_version | 11 |

## Test case: Use Swipe right (or alt+right arrow) (Read next item) to navigate forward to `*[aria-current="location"]`
Command used: `next_item`

### output
**before:**
```"Phone numbers, link"```
**after:**
```"Phone numbers, current location link"```

### result for aria-current attribute, MUST convey the "location" value, applied to hyperlink element

key: aria/aria-current_attribute; convey_value_location; applied to: html/a(href)_element

### result
**before:**
```fail```
**after:**
```pass```

### note
**before:**
```(empty)```
**after:**
```Working as expected```

## Test case: Use Swipe right (or alt+right arrow) (Read next item) to navigate forward to `*[aria-current="page"]`
Command used: `next_item`

### output
**before:**
```"home, link"```
**after:**
```"home, current page link"```

### result for aria-current attribute, MUST convey the "page" value, applied to hyperlink element

key: aria/aria-current_attribute; convey_value_page; applied to: html/a(href)_element

### result
**before:**
```fail```
**after:**
```pass```

### note
**before:**
```(empty)```
**after:**
```Working as expected```

## Test case: Use Swipe right (or alt+right arrow) (Read next item) to navigate forward to `*[aria-current="step"]`
Command used: `next_item`

### output
**before:**
```"do this, link"```
**after:**
```"do this, current step link"```

### result for aria-current attribute, MUST convey the "step" value, applied to hyperlink element

key: aria/aria-current_attribute; convey_value_step; applied to: html/a(href)_element

### result
**before:**
```fail```
**after:**
```pass```

### note
**before:**
```(empty)```
**after:**
```Working as expected```

## Test case: Use Swipe right (or alt+right arrow) (Read next item) to navigate forward to `*[aria-current="true"]`
Command used: `next_item`

### output
**before:**
```"apples, link"```
**after:**
```"apples, current item link"```

### result for aria-current attribute, MUST convey the "true" value, applied to hyperlink element

key: aria/aria-current_attribute; convey_value_true; applied to: html/a(href)_element

### result
**before:**
```fail```
**after:**
```pass```

### note
**before:**
```(empty)```
**after:**
```Working as expected```

**Comment by RavenAlly** [comment]
Can this issue be closed since TalkBack / Android / aria-current was updated in #194 ?

**Comment by mfairchild365** [comment]
Yep, thank you!
