### ISSUE TITLE
Listing same browser in both core and extended for AT duplicates results

### ISSUE THREAD

**Issue by RavenAlly** [accessibilitysupported/a11ysupport.io#206]
In [ATBrowsers.json](https://github.com/accessibilitysupported/a11ysupport.io/blob/master/data/ATBrowsers.json), each assistive tech has `core_browsers` and `extended_browsers` listed.

When the same browser is listed in both `core_browsers` and `extended_browsers` for a given AT, detailed support results for that AT / browser combination are duplicated. Most obvious examples are JAWS / Edge and NVDA / Edge.

**Comment by mfairchild365** [comment]
This is a bug and core/extended should be mutually exclusive. For JAWS/NVDA, edge should be listed as core but not extended. Are you interested in fixing this?

**Comment by RavenAlly** [comment]
If it's as simple as removing the duplicate entries from ATBrowsers.json, then sure! I wasn't sure if there was more to do behind the scenes.
