### ISSUE TITLE
Slow, unusable searches

### ISSUE THREAD

**Issue by anevins12** [accessibilitysupported/a11ysupport.io#227]
I'm finding the search feature causes the page to crash. If not, it is left on an infinitely loading spinny wheel. I'm in Chrome.

**Comment by mfairchild365** [comment]
Thank you for reporting this @anevins12. I've tried to reproduce the problem, but can't. Can you provide some steps that I can follow?

**Comment by anevins12** [comment]
Ah it's an issue with one of my Chrome addons. Annoying, but thank you for your quick response
