### ISSUE TITLE
html_label_element_implicit vc_macos/safari

### ISSUE THREAD

**Issue by Aircl0wn** [accessibilitysupported/a11ysupport.io#249]
This Support Point submission is for the test [Implicit label](/tests/html_label_element_implicit)

meta info

| property | value |
| --- | --- |
| title | html_label_element_implicit |
| at | vc_macos |
| at_version | 12.6.1 |
| browser | safari |
| browser_version | 16.1 |
| os_version | 12.6.1 |

no changes (same results were confirmed)

**Comment by mfairchild365** [comment]
Updated in https://github.com/accessibilitysupported/a11ysupport.io/commit/e80703e378b07f57d587a0c59f956f58a553d643
