### ISSUE TITLE
Testcase for announcement of groupings

### ISSUE THREAD

**Issue by andypillip** [accessibilitysupported/a11ysupport.io#256]
See also https://stackoverflow.com/questions/74730865/when-and-based-on-which-specification-do-screen-readers-announce-a-group-name

The ARIA standard offers the `group` and the `region` roles to group contents or user interface objects.

Both require a name provided by author, and screen readers seem to announce when such a grouping is entered or left, announcing the grouping‘s name on enter. This also applies for other roles such as list or dialog.

This is very practical, and it would be great to know the support status for interface design.

**Comment by mfairchild365** [comment]
Hi @andypillip - we do have tests for such boundaries. See the [group role](https://a11ysupport.io/tech/aria/group_role) as an example. There are similar expectations for many other roles.

Is this what you are asking?

**Comment by andypillip** [comment]
Hei Michael.

Thanks for the answer. Yes, that’s what I’m asking. [Convey the boundaries of the group](https://a11ysupport.io/tech/aria/group_role#support-table-2) is exactly what I’m after.

Is there an exhaustive list in some standard of which roles have that expectation?

Thanks
