### ISSUE TITLE
Abstract role tests should be removed

### ISSUE THREAD

**Issue by cookiecrook** [accessibilitysupported/a11ysupport.io#289]
widget role tests should be removed (abstract role)

> widget is an [abstract role](https://w3c.github.io/aria/#isAbstract) used for the ontology. Authors MUST NOT use widget role in content.

Cite: https://w3c.github.io/aria/#widget

**Comment by cookiecrook** [comment]
https://a11ysupport.io/tech/aria/widget_role

**Comment by cookiecrook** [comment]
Ditto `sectionhead` https://a11ysupport.io/tech/aria/sectionhead_role

**Comment by cookiecrook** [comment]
- https://a11ysupport.io/tech/aria/roletype_role

**Comment by cookiecrook** [comment]
- https://a11ysupport.io/tech/aria/range_role

**Comment by mfairchild365** [comment]
Thank you for pointing this out @cookiecrook! It has been fixed.
