### ISSUE TITLE
tech/aria/role-group-unnamed nvda/chrome

### ISSUE THREAD

**Issue by SimoAccessiWay** [accessibilitysupported/a11ysupport.io#295]
This Support Point submission is for the test [ARIA - unnamed group role test](/tests/tech__aria__role-group-unnamed)

meta info

| property | value |
| --- | --- |
| title | tech/aria/role-group-unnamed |
| at | nvda |
| at_version | 2024.3 |
| browser | chrome |
| browser_version | 129 |
| os_version | Windows 11 version 23H2 |

no changes (same results were confirmed)

**Comment by mfairchild365** [comment]
Thank you @SimoAccessiWay!
