### ISSUE TITLE
html_label_element_explicit_aam vo_macos/chrome

### ISSUE THREAD

**Issue by Shaderpixel** [accessibilitysupported/a11ysupport.io#4]
| property | value |
| --- | --- |
| title | html_label_element_explicit_aam |
| support | y |
| at | vo_macos |
| at_version | 10.13.6  |
| os_version | 10.13.6  |
| browser | chrome |
| browser_version | 68.0.3440.84 |
| output_1_command | VO + Right Arrow |
| output_1_output | Your Name, Edit Text |
| output_1_result | pass |
| output_2_command | VO + Shift + Right Arrow |
| output_2_output | Your Name, Edit Text |
| output_2_result | pass |

**Comment by mfairchild365** [comment]
Awesome, thank you! Did you notice if pressing the tab key to access the input yields the same result?

**Comment by mfairchild365** [comment]
I got the same results and tested the tab key too.

| property | value |
| --- | --- |
| title | html_label_element_explicit_aam |
| support | y |
| at | vo_macos |
| at_version | 10.13.6 |
| os_version | 10.13.6 |
| browser | chrome |
| browser_version | 11.1.2 |
| output_1_command | VO + right arrow |
| output_1_output | Your name, edit text |
| output_1_result | pass |
| output_2_command | VO + shift + right/left arrow |
| output_2_output | Your name, edit text |
| output_2_result | pass |
| output_3_command | tab |
| output_3_output | Your name, edit text |
| output_3_result | pass |
