### ISSUE TITLE
html_svg_inline_with_title_aam narrator/edge

### ISSUE THREAD

**Issue by mfairchild365** [accessibilitysupported/a11ysupport.io#57]
This Support Point submission is for the test [HTML SVG element with SVG title element](/tests/html_svg_inline_with_title_aam)

| property | value |
| --- | --- |
| title | html_svg_inline_with_title_aam |
| at | narrator |
| browser | edge |
| at_version | 1809 |
| os_version | 1809 |
| browser_version | 44 |
| output_1_command | next_item |
| output_1_output | (target not announced) |
| output_1_result | fail |

**Comment by mfairchild365** [comment]
Note: 1809 is the windows 10 build number.

**Comment by weboverhauls** [comment]
It was Win 10 OS build 16299.522.
Funny, I just added this info to my test page (under Notes).
