### ISSUE TITLE
aria/dialog_role: add supported with talkback

### ISSUE THREAD

**Issue by scottaohara** [accessibilitysupported/a11ysupport.io#62]
Can confirm that `dialog` role is understood and announced by TalkBack 7.2 on an Android 8.1 device.

Reproduce:
* with talkback on, navigate [the test page](https://scottaohara.github.io/accessible_modal_window/) to the launch modal button.
* activate the button and focus will be moved to the dialog element, where the role will be announced.

**Comment by mfairchild365** [comment]
@scottaohara I actually don't have any test cases to ensure that the dialog role is announced right now. is this in reference to https://a11ysupport.io/tests/aria_dialog_document_mode which asserts that the dialog role must not trigger the screen reader to switch from brwose mode to application mode?

**Comment by mfairchild365** [comment]
Fixed per our conversation (not on GitHub)
