### ISSUE TITLE
Report for html label element with CSS generated content w/JAWS and Firefox

### ISSUE THREAD

**Issue by scottaohara** [accessibilitysupported/a11ysupport.io#63]
This Support Point submission is for the test [HTML label with CSS generated content](/tests/html_label_element_css_content)

| property | value |
| --- | --- |
| title | html_label_element_css_content |
| at | dragon_win |
| browser | ie |
| at_version | JAWS 2019 |
| os_version | Windows 10 |
| browser_version | Firefox 65.0.1 |
| output_1_command | activate_actionable_item |
| output_1_output | "This is generated content, clickable" when accessed by Virtual cursor.   "This is generated content, edit" when focusing the text input. |
| output_1_result | pass |

== begin notes ==
all content from the label (whether generated or not) becomes part of the input's accessible name and is announced by JAWS 2019 with Firefox 65.0.1 in both browse and forms mode.
== end notes ==

**Comment by mfairchild365** [comment]
Edited version of above. Switched the AT to JAWS, broke the two commands used into seperate output rows.

| property | value |
| --- | --- |
| title | html_label_element_css_content |
| at | jaws |
| browser | ie |
| at_version | JAWS 2019 |
| os_version | Windows 10 |
| browser_version | Firefox 65.0.1 |
| output_1_command | next_item |
| output_1_output | "This is generated content, clickable" |
| output_1_result | pass |
| output_2_command | next_focusable_item |
| output_2_output | "This is generated content, edit" |
| output_2_result | pass |

== begin notes ==
all content from the label (whether generated or not) becomes part of the input's accessible name and is announced by JAWS 2019 with Firefox 65.0.1 in both browse and forms mode.
== end notes ==
