### ISSUE TITLE
Typo in link to external test pages

### ISSUE THREAD

**Issue by jfhector** [accessibilitysupported/a11ysupport.io#67]
On test pages under the 'Test HTML' heading, the link to external text pages reads:
'view the external text'.

I believe that it should read like this instead:
'View the external test'.

Ie. the link uses the word 'text', while I believe it should use the word 'test'.

[Example](https://a11ysupport.io/tests/tech__checkbox-two-state)

**Comment by mfairchild365** [comment]
@jfhector thank you for reporting this!
