### ISSUE TITLE
tech/aria/aria-details talkback/and_chr

### ISSUE THREAD

**Issue by jfhector** [accessibilitysupported/a11ysupport.io#69]
This Support Point submission is for the test [aria-details test](/tests/tech__aria__aria-details)

meta info

| property | value |
| --- | --- |
| title | tech/aria/aria-details |
| at | talkback |
| at_version | TalkBack included in Android 8.0.0 |
| browser | and_chr |
| browser_version | Chrome 75 |
| os_version | Android 8.0.0 |

aria-details attribute / The screen reader MUST convey the presence of aria-details

| property | value |
| --- | --- |
| feature_id | aria/aria-details_attribute |
| feature_assertion_id | convey_presence |
| output_1_command | next_item |
| output_1_from | before target |
| output_1_to | target |
| output_1_output | Pythagorean Theorem, graphic |
| output_1_result | fail |

aria-details attribute / The screen reader SHOULD allow the user to jump to the referenced element

| property | value |
| --- | --- |
| feature_id | aria/aria-details_attribute |
| feature_assertion_id | allow_jump_to |
| output_1_command | next_item |
| output_1_from | before target |
| output_1_to | target |
| output_1_output | Pythagorean Theorem, graphic |
| output_1_result | fail |

aria-details attribute / The screen reader SHOULD allow the user to jump back to the referencing element

| property | value |
| --- | --- |
| feature_id | aria/aria-details_attribute |
| feature_assertion_id | allow_jump_back |
| output_1_command | next_item |
| output_1_from | before target |
| output_1_to | target |
| output_1_output | Pythagorean Theorem, graphic |
| output_1_result | fail |

aria-details attribute / The screen reader MAY convey the boundaries of the details

| property | value |
| --- | --- |
| feature_id | aria/aria-details_attribute |
| feature_assertion_id | convey_details_boundaries |
| output_1_command | next_item |
| output_1_from | before target |
| output_1_to | target |
| output_1_output | Details about the Pythagorean Theorem image (i.e. TalkBack read the text content itself) |
| output_1_result | fail |

**Comment by jfhector** [comment]
I wasn't sure what the word 'target' referred to in the drop down menus for the last assertion ("The screen reader MAY convey the boundaries of the details").

i.e. in the previous assertions, I believe that the 'target' was the `img` element.

But for this last assertion, I wasn't sure whether the 'target' should be the `p` element referenced by the `aria-details` attribute, or the same target as for the previous assertions.

I figured it was the former, but I wasn't sure whether I was performing the test right.

**Comment by mfairchild365** [comment]
@jfhector Thank you for this data! I'll incorporate it soon. 

And thank you for the feedback on the word 'target' within the dropdowns. 'target' refers to the element that matches the CSS selector for each assertion. I'll have a think on how to make this easier to understand. In this case, it was the `p` with the id of `details`.
