### ISSUE TITLE
HTML label element - explicit: Voice Access / Google Chrome (Android 8.0)

### ISSUE THREAD

**Issue by carrythebanner** [accessibilitysupported/a11ysupport.io#84]
This Support Point submission is for the test [Explicit label](/tests/html_label_element_explicit)

meta info

| property | value |
| --- | --- |
| title | html_label_element_explicit |
| at | va_and |
| at_version | 3.1 |
| browser | and_chr |
| browser_version | 77 |
| os_version | 8.0 |

**Comment by mfairchild365** [comment]
Thank you @carrythebanner!
