### ISSUE TITLE
Test aria-live

### ISSUE THREAD

**Issue by mfairchild365** [accessibilitysupported/a11ysupport.io#85]
We should set up tests for aria-live and associated attributes.

Set up the feature and expectation for [aria-live](https://www.w3.org/TR/wai-aria-1.1/#aria-live)
- [x] MUST convey value `off`
- [x] MUST convey value `polite`
- [x] MUST convey value `assertive`

Set up the feature and expectation for [aria-atomic](https://www.w3.org/TR/wai-aria-1.1/#aria-atomic)
- [x] MUST convey value `false`
- [x] MUST convey value `true`

Set up the feature and expectation for [aria-relevant](https://www.w3.org/TR/wai-aria-1.1/#aria-relevant)
- [x] MUST convey value `additions`
- [x] MUST convey value `additions text`
- [x] MUST convey value `all`
- [x] MUST convey value `removals`
- [x] MUST convey value `text`

Other tasks

- [x] Set up test HTML file(s) for the above attributes and values
- [x] Set up a test JSON file
- [x] Run tests and submit results for all core at/browser combos

**Comment by mfairchild365** [comment]
@straker contributed some results for `aria-live` in #102

**Comment by straker** [comment]
Issue can be closed now. Aria-atomic added in #107 and aria-relevant added in #110

**Comment by mfairchild365** [comment]
Thank you again, @straker!
