### ISSUE TITLE
Confusion around test result inconsistencies between pages

### ISSUE THREAD

**Issue by jfhector** [accessibilitysupported/a11ysupport.io#96]
#### Example 1

On the [table named "Screen Reader support for 'MUST convey an appropriate role'"](https://a11ysupport.io/tech/html/li_element#support-table-0), the row for "HTML Ordered list test" indicates partial support with JAWS, NVDA and Talkback.

When I then click on the "HTML Ordered list test" link and arrived at the ["Expectation for the li element: convey an appropriate role" section of a different page](https://a11ysupport.io/tests/tech__html__ol#assertion-html-li_element-convey_role), the test result table in that section all indicate "Yes / Green" for JAWS, NVDA and Talkback.

#### Example 2

On the [table named "Expectation: convey the "true" value'"](https://a11ysupport.io/tech/aria/aria-disabled_attribute#support-table-1), the row for "HTML button[type="button" aria-disabled="true" aria-haspopup="true"]" indicates partial support with TalkBack and iOS VoiceOver.

When I then click on the "HTML button[type="button" aria-disabled="true" aria-haspopup="true"]" link and arrived at the ["Expectation for the aria-disabled attribute: convey the "true" value" section of a different page](https://a11ysupport.io/tests/html_button(type-button--aria-disabled-true--aria-haspopup-true)#assertion-aria-aria-disabled_attribute-convey_value_true), the test result table in that section indicate "Yes / Green" for Talkback and "None / Red" for iOS VoiceOver.

I expected these test results to be "Partial" for both Talkback and iOS VoiceOver, as indicated on the previous page.

#### Example 2b

On the [table named "Expectation: convey the "true" value'"](https://a11ysupport.io/tech/aria/aria-disabled_attribute#support-table-1), the row for "HTML button[type="button" aria-disabled="true"]" indicates partial support with TalkBack and iOS VoiceOver.

When I then click on the "HTML button[type="button" aria-disabled="true"]" link and arrived at the ["Expectation for the aria-disabled attribute: convey the "true" value" section of a different page](https://a11ysupport.io/tests/html_button(type-button--aria-disabled-true)#assertion-aria-aria-disabled_attribute-convey_value_true), the test result table in that section indicate "No / Red" for Talkback and "Yes / Green" for iOS VoiceOver.

I expected these test results to be "Partial" for both Talkback and iOS VoiceOver, as indicated on the previous page.

**Comment by mfairchild365** [comment]
Thanks for reporting this @jfhector - it has been fixed

**Comment by jfhector** [comment]
Yes, it's fixed! Great!
